import React from 'react';
import useTitle from '../../Hook/useTitle';

const Blogs = () => {

    useTitle('Toyland Junction | Blogs')

    return (
        <div>

            {/* question 1 */}
            <div className='bg-base-200 p-8 rounded-lg my-12'>
                <h2 className="text-2xl font-semibold">Q1- What is an access token and refresh token? How do they work and where should we store them on the client-side?</h2>

                <p className='bg-base-300 p-4 m-4 rounded-md'>
                    Access Token and Refresh Token both used in Authorization and Authentication to manage user access to confidential data.
                    <br /><br />
                    <span className='font-bold'>Access Token: </span>
                    Access token is generated by server upon a successful authentication of a user. It is used to authorize the access of the user. Access token is short term and had an expiration period. Once the expiration is over it becomes useless.
                    <br /><br />
                    <span className='font-bold'>Refresh Token: </span>
                    Along with the access token, the authentication server will also issue refresh token. The refresh token is not used to access resources directly, comparing it with the access token. Instead, it is utilized to get a fresh access token when the old one runs out.
                    <br /><br />
                    An access token is generated by the authentication server and given to the client application when a user logs in or authenticates with a system. When the access token expires, the client application can use the refresh token to request a new access token from the authentication server. This process is called token refresh. The server first verify the refresh token, if the token is valid then generates a access token and send it to the client application.
                    <br /><br />
                    Tokens are mainly stored in client side. They should be stored in a way that prevents unauthorized access. It can use either local storage or browser cookies http only.


                </p>
            </div>

            {/* question 2 */}
            <div className='bg-base-200 p-8 rounded-lg my-12'>
                <h2 className="text-2xl font-semibold">Q2- Compare SQL and NoSQL databases?</h2>

                <table className="table w-full">
                    <thead >
                        <tr className='text-2xl'>
                            <th>SQL</th>
                            <th>No SQL</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Stands for Structured Query Language.</td>
                            <td>Stands for Not only SQL</td>
                        </tr>
                        <tr>
                            <td>Uses relational data structure</td>
                            <td>Uses non-relational data structure</td>
                        </tr>
                        <tr>
                            <td>Data stored in table with rows and columns.</td>
                            <td>Data stored in collections and documents.</td>
                        </tr>
                        <tr>
                            <td>Uses normalized data structure</td>
                            <td>Uses denormalized data structure</td>
                        </tr>
                        <tr>
                            <td>Examples: MySQL, PostgreSQL, Oracle, SQL Server, Microsoft SQL Server</td>
                            <td>Examples: MongoDB, Cassandra, Couchbase, Amazon DynamoDB, Redis</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            {/* question 3 */}
            <div className='bg-base-200 p-8 rounded-lg my-12'>
                <h2 className="text-2xl font-semibold">Q3- What is Express js? What is Nest js?</h2>

                <p className='bg-base-300 p-4 m-4 rounded-md'>
                    
                    <span className='font-bold'>Express js: </span>
                    Express is a flexible and minimal Node.js framework that offers a wide range of functionality to develop mobile and web apps. It is a simple, minimalist framework that lets programmers use the tools and libraries of their choice to construct applications. Express is very popular among developers due to its simplicity and ease of use.
                    <br /><br />
                    <span className='font-bold'>Nest js: </span>
                    For the purpose of creating effective, scalable, and dependable server-side applications, NestJS is a progressive Node.js framework. It offers a more structured method of creating TypeScript apps and is built on top of Express.js. The modular architecture of NestJS makes it simple to maintain and scale apps as they get bigger.

                </p>
            </div>

            {/* question 4 */}
            <div className='bg-base-200 p-8 rounded-lg my-12'>
                <h2 className="text-2xl font-semibold">Q4- What is MongoDB aggregate and how does it work?</h2>

                <p className='bg-base-300 p-4 m-4 rounded-md'>
                    
                Aggregation is the process of going through various phases with a huge collection of documents to process them. A pipeline is made up of the several stages. Filtering, sorting, grouping, reshaping, and altering documents as they move through a pipeline are all possible.
                <br /><br />
                Calculating aggregate values for collections of documents is one of Aggregation's most often used use cases. This is comparable to the fundamental aggregation offered by the GROUP BY clause and the COUNT, SUM, and AVG functions in SQL. However, MongoDB Aggregation takes a step further and can also conduct joins that resemble those in a relational database, restructure documents, create and edit existing collections, and more. 
                <br /><br />
                


                </p>
            </div>


        </div>
    );
};

export default Blogs;